import { ProgrameProvider } from "@/context/programContext";
import "./globals.css";

export const metadata = {
  title: "Rendzous Screening",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProgrameProvider>
          {children}
        </ProgrameProvider>
      </body>
    </html>
  );
}
